name: Docker Image CI

on:
  workflow_run:
    workflows: ["Lint Code Base"]
    types:
      - completed

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker-base:$(date +%s)
